### ISSUE TITLE
tex-work/inf/AboutClasses.txt

### ISSUE THREAD

**Issue by gmaksimov** [imustafin/CutTesseract#12]
Проверить, исправить, дописать.

**Comment by imustafin** [comment]
Это надо в самом коде писать.
Гугли Javadoc

**Comment by anugmanov** [comment]
иди в жопу

03.02.2015, 19:04, "Ilgiz Mustafin" notifications@github.com:

**Comment by imustafin** [comment]
@anugmanov, ты тупой? Ладно, для наачала можно и сюда, но потом точно в код.

**Comment by anugmanov** [comment]
бля я не хочу лазить в коде. Мне нужен этот файл ЗДЕСЬ, ок?

03.02.2015, 22:22, "Ilgiz Mustafin" notifications@github.com:

**Comment by imustafin** [comment]
Гуглим Javadoc.
Если правильно закомментировать что-то в коде, то потом можно автоматически создать красивую ХТМЛку со всеми комментами

**Comment by anugmanov** [comment]
TEX!=HTML

03.02.2015, 23:02, "Ilgiz Mustafin" notifications@github.com:

**Comment by imustafin** [comment]
Даладно?
Потом красиво скопипастишь

**Comment by imustafin** [comment]
Короче, c259fbfdf041ae90e53636cee86be6d90629a3de смотри, окда?
Там есть в папке **javadoc** хтмлки, можешь их посмотреть. Еще можешь почитать в интернете про экспорт javadoc в TeX, конкретно про доклеты
