### ISSUE TITLE
Описание работы программы

### ISSUE THREAD

**Issue by gmaksimov** [imustafin/CutTesseract#18]
Описание работы программы:

Описание работы программы
Скриншоты программы
Примеры работы
Возможности программы.

**Comment by gmaksimov** [comment]
В программу включена возможность поворота трехмерного сечения для лучшего его понимания, а также опция скрытия гиперкуба. Чтобы было удобнее задавать гиперплоскость сечения, в программу был добавлен графический интерфейс (Java swing) для задания и редактирования четырехмерного вектора и точки. Снизу окна были добавлены панели введения координат мышкой интерактивно или клавиатурой для упрощения процесса задания четырехмерных точки и вектора.

**Comment by gmaksimov** [comment]
Мы же еще проецируем  на двумерную плоскость монитора - тоже можно написать наверное

**Comment by imustafin** [comment]
Блин, в мастере было
