### ISSUE TITLE
Bugs in main_math.tex

### ISSUE THREAD

**Issue by gmaksimov** [imustafin/CutTesseract#19]
На титульной странице имя Максимов Григория должно быть первым
на странице 7 формулы (4) и (5) нужно поменять местами, при определении матрицы поворота zw и yz поменять местами
Последняя страница - убрать из списка литературы coolreferat.com

**Comment by gmaksimov** [comment]
P.S. Не забудь скомпилить 2 раза

**Comment by gmaksimov** [comment]
*На титульной странице в информатике Ильгиз первый, в матем я.

**Comment by anugmanov** [comment]
У тебя мания величия

**Comment by gmaksimov** [comment]
Нет, маресль абый сказал так
