### ISSUE TITLE
Марсель абый сказал

### ISSUE THREAD

**Issue by gmaksimov** [imustafin/CutTesseract#21]
1 слайд: добавить научн. рук.
4 слайд: поменять рисунок №1
5 слайд: рисунок
6 слайд: точки вставить
8 слайд: точЕК, ребра вершины (в конце)
11 слайд: добавить >=, добаить + 2
12 слайд: убрать доказательство (мб вставить картинку)
13 слайд: картинка
14  слайд: переделать (гепотиза)

**Comment by anugmanov** [comment]
иди в жопу

18.03.2015, 18:46, "gmaksimov" notifications@github.com:

**Comment by anugmanov** [comment]
иди в жопу

18.03.2015, 18:46, "gmaksimov" notifications@github.com:

**Comment by anugmanov** [comment]
баг №1,4,5 пофиксил
